# OperationsCenter:
#   ExtraConfigMaps:
#   - name: oc-casc-bundle
#     labels:
#       key1: value1
#     annotations:
#       key1: value1
#     data:
#        myfile.yaml: |
#          foo: bar  
#   CasC:
#     # OperationsCenter.CasC.Enabled -- enable or disable CasC for Operations Center.
#     Enabled: true
#     # OperationsCenter.CasC.ConfigMapName -- the name of the ConfigMap used to configure Operations Center.
#     # Note: this property can point to a ConfigMap defined in OperationsCenter.ExtraConfigMaps,
#     # or any ConfigMap that exists in the cluster.
#     ConfigMapName: oc-casc-bundle
#     # casc-retriever (optional)
#     Retriever:
#       # OperationsCenter.Casc.Retriever.Enabled -- Whether to enable installation of the casc-retriever for the OC
#       # may not be enabled if fips140 is true
#       Enabled: false
#       image:
#         # OperationsCenter.Casc.Retriever.image.registry -- Docker registry for Casc Retriever
#         registry: docker.io
#         # OperationsCenter.CasC.Retriever.image.repository -- Docker image repository for Casc Retriever
#         repository: cloudbees/casc-scm-bundle-retriever
#         # OperationsCenter.CasC.Retriever.image.tag -- Docker image tag for Casc Retriever
#         tag: 1.0.22
#         # OperationsCenter.CasC.Retriever.image.pullPolicy -- https://kubernetes.io/docs/concepts/containers/images/#updating-images
#         pullPolicy: IfNotPresent
#       Resources:
#         Limits:
#           # override with OperationsCenter.CasC.Retriever.Resources.Limits.Cpu -- CPU limit to run Casc Retriever
#           # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu
#           Cpu: .25
#           # override with OperationsCenter.CasC.Retriever.Resources.Limits.Memory -- Memory limit to run CasC Retriever
#           # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
#           Memory: 512M
#           # override with OperationsCenter.CasC.Retriever.Resources.Limits.EphemeralStorage -- Ephemeral Storage limit to run CasC Retriever
#           # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
#           # EphemeralStorage: null
#         Requests:
#           # override with OperationsCenter.CasC.Retriever.Resources.Requests.Cpu -- CPU request to run CasC Retriever
#           # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu
#           Cpu: .25
#           # override with OperationsCenter.CasC.Retriever.Resources.Requests.Memory -- Memory request to run CasC Retriever
#           # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
#           Memory: 512M
#           # override with OperationsCenter.CasC.Retriever.Resources.Requests.EphemeralStorage -- Ephemeral Storage request to run CasC Retriever
#           # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
#           # EphemeralStorage: null
#       # ContainerPort -- Container port for http traffic for the CasC Retriever, the default value of 9090 should work for most deployments
#       containerPort: 9090
#       # OperationsCenter.CasC.Retriever.scmRepo -- The url of the repo containing the casc bundle
#       scmRepo: REPOSITORY
#       # OperationsCenter.CasC.Retriever..scmBranch -- The branch of the repo containing the casc bundle
#       scmBranch: BRANCH
#       # OperationsCenter.CasC.Retriever.scmBundlePath -- path to a folder within the repo where the bundle.yaml is located
#       scmBundlePath: "/"
#       # OperationsCenter.CasC.Retriever.ocBundleAutomaticVersion -- if true, the commit hash will replace the version of the bundle from the SCM
#       ocBundleAutomaticVersion: "false"
#       # OperationsCenter.CasC.Retriever.scmPollingInterval -- How frequently to poll SCM for changes
#       # Interval is specified using standard java Durataion format
#       # (see https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-)
#       scmPollingInterval: "PT20M"
#       # OperationsCenter.CasC.Retriever.githubWebhooksEnabled -- Indicates if Github webhook support is activated
#       githubWebhooksEnabled: "true"
#       # OperationsCenter.CasC.Retriever.emailBundleUpdateActive -- Enabled email notifications of new bundles
#       emailBundleUpdateActive: "false"
#       # OperationsCenter.CasC.Retriever.emailUpdateSubject -- If using email notifications, subject of the mail
#       emailUpdateSubject: null
#       # OperationsCenter.CasC.Retriever.emailBundleUpdateBody -- If using email notifications, body of the mail
#       emailBundleUpdateBody: null
#       # OperationsCenter.CasC.Retriever.emailBundleUpdateList -- If using email notifications, "to" list of mails of the mail
#       emailBundleUpdateList: null
#       # OperationsCenter.CasC.Retriever.smtpAuthMethods -- If using email notifications, smtp authentication methods, one or more from DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
#       smtpAuthMethods: null
#       # OperationsCenter.CasC.Retriever.emailBundleUpdateFrom -- If using email notifications, mail sender
#       emailBundleUpdateFrom: null
#       # OperationsCenter.CasC.Retriever.smtpHost -- If using email notifications, hostname of the STMP server
#       smtpHost: null
#       # OperationsCenter.CasC.Retriever.smtpPort -- If using email notifications, port of the SMTP server
#       smtpPort: null
#       # OperationsCenter.CasC.Retriever.smtpStartTls -- If using email notifications, usage of Transport Layer Security, posible values are REQUIRED or OPTIONAL
#       smtpStartTls: null
#       # OperationsCenter.CasC.Retriever.secrets -- Allows you to customize the key used for each secret value
#       secrets:
#         # OperationsCenter.CasC.Retriever.secrets.secretName -- Define the name of the object that holds the secrets, defaults to casc-retriever-secrets if not specified
#         secretName: null
#         # OperationsCenter.CasC.Retriever.secrets.scmUsername -- SCM username to authenticate against the repo
#         scmUsername: null
#         # OperationsCenter.CasC.Retriever.secrets.scmPassword -- SCM password / token used in user authentication in the repo
#         scmPassword: null
#         # OperationsCenter.CasC.Retriever.secrets.sshConfig -- SCM SSH credentials, if using SSh credentials to connect to SCM you'll need to provide a a secret with .ssh contents, including config, private key and known_hosts that allow ssh authentication.
#         # Indicate the name of the secret to use.
#         # CasC SCM retriever only supports keys in OpenSSH format.
#         sshConfig: null
#         # OperationsCenter.CasC.Retriever.secrets.githubWebhookSecret -- If Github webhooks will be using a secret, set it up here. If not indicated all webhooks from configured repository + branch will be accepted
#         githubWebhookSecret: null
#         # OperationsCenter.CasC.Retriever.secrets.smtpUsername -- If using email notifications, username for the SMTP server authentication
#         smtpUsername: null
#         # OperationsCenter.CasC.Retriever.secrets.smtpPassword -- If using email notifications, password for the SMTP server authentication
#         smtpPassword: null
#         # OperationsCenter.CasC.Retriever.secrets.adminPassword -- Secret containing password for accessing retriever internal endpoints
#         adminPassword: null